"""is admin

Revision ID: 48516a085299
Revises: 5db5b6321791
Create Date: 2025-04-13 15:00:36.564369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48516a085299'
down_revision = '5db5b6321791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
