"""empty message

Revision ID: 55d438a57094
Revises: 1c94b7adc18b
Create Date: 2025-04-18 20:49:19.797572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55d438a57094'
down_revision = '1c94b7adc18b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_achievements_title'), ['title'], unique=True)
        batch_op.create_index(batch_op.f('ix_achievements_value'), ['value'], unique=False)

    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('post', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_post'), ['post'], unique=False)

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desc', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('early', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('url', sa.String(length=64), nullable=False))
        batch_op.create_index(batch_op.f('ix_game_desc'), ['desc'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_url'), ['url'], unique=True)
        batch_op.drop_column('betatest')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('betatest', sa.BOOLEAN(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_game_url'))
        batch_op.drop_index(batch_op.f('ix_game_desc'))
        batch_op.drop_column('url')
        batch_op.drop_column('early')
        batch_op.drop_column('desc')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_post'))
        batch_op.drop_index(batch_op.f('ix_employees_last_name'))
        batch_op.drop_index(batch_op.f('ix_employees_first_name'))

    op.drop_table('employees')
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_achievements_value'))
        batch_op.drop_index(batch_op.f('ix_achievements_title'))

    op.drop_table('achievements')
    # ### end Alembic commands ###
