"""empty message

Revision ID: 6002de9e2f96
Revises: d82345e30f5a
Create Date: 2025-04-23 21:07:32.918681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6002de9e2f96'
down_revision = 'd82345e30f5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_index('ix_game_url')
        batch_op.create_index(batch_op.f('ix_game_url'), ['url'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_url'))
        batch_op.create_index('ix_game_url', ['url'], unique=1)

    # ### end Alembic commands ###
