"""empty message

Revision ID: 5c6b6257c229
Revises: 55d438a57094
Create Date: 2025-04-18 21:29:24.223380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c6b6257c229'
down_revision = '55d438a57094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_achievement_title'), ['title'], unique=True)
        batch_op.create_index(batch_op.f('ix_achievement_value'), ['value'], unique=False)

    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('post', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_post'), ['post'], unique=False)

    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.drop_index('ix_achievements_title')
        batch_op.drop_index('ix_achievements_value')

    op.drop_table('achievements')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index('ix_employees_first_name')
        batch_op.drop_index('ix_employees_last_name')
        batch_op.drop_index('ix_employees_post')

    op.drop_table('employees')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('post', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index('ix_employees_post', ['post'], unique=False)
        batch_op.create_index('ix_employees_last_name', ['last_name'], unique=False)
        batch_op.create_index('ix_employees_first_name', ['first_name'], unique=False)

    op.create_table('achievements',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=64), nullable=False),
    sa.Column('value', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.create_index('ix_achievements_value', ['value'], unique=False)
        batch_op.create_index('ix_achievements_title', ['title'], unique=1)

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_post'))
        batch_op.drop_index(batch_op.f('ix_employee_last_name'))
        batch_op.drop_index(batch_op.f('ix_employee_first_name'))

    op.drop_table('employee')
    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_achievement_value'))
        batch_op.drop_index(batch_op.f('ix_achievement_title'))

    op.drop_table('achievement')
    # ### end Alembic commands ###
